const fs = require('fs');
const DATA = 'public/data';

const cmEntries = [
  {"name":"Vishen Lakhiani","source":"non-founder","domain":"personal growth / consciousness education / edtech","oneLiner":"Built a $100M personal growth university from a $700 laptop in a Starbucks, without ever taking a dollar of venture capital.","primaryProblem":"feeling_stupid","primarySkills":["leading","teaching","building"],"careerModel":{"type":"edtech_platform_empire","primaryRevenue":"Membership subscriptions and cohort-based Quests","revenueStreams":["membership subscriptions","cohort-based Quests","coaching certifications","live festivals (A-Fest)","books","premium coaching","Mindvalley University"],"trajectory":"Computer engineering grad moved to Silicon Valley at 25, started Mindvalley with $700 at 26, bootstrapped for 14 years, first book at 40 exploded revenue, scaled to $100M and 20M students by 49.","keyDecision":"Refused venture capital entirely, bootstrapping to $100M so he could keep Mindvalley's mission pure.","scaleModel":"Free masterclasses build audience, subscription Quests create recurring revenue, certified coaches extend the brand, festivals build community loyalty.","lessonsForUser":"If you teach and care about personal growth: build a platform that curates other teachers, not just your own content. You become the stage, not the act."},"confidence":"high"},
  {"name":"Michael Singer","source":"non-founder","domain":"meditation / surrender philosophy / inner freedom","oneLiner":"A PhD dropout who built a billion-dollar software company by accident while trying to sit quietly in the woods.","primaryProblem":"life_not_yours","primarySkills":["teaching","building","storytelling"],"careerModel":{"type":"author_teacher_community","primaryRevenue":"Book royalties and online courses","revenueStreams":["book royalties","online courses","podcast","community donations","speaking engagements"],"trajectory":"Spiritual awakening during economics PhD at 24, founded Temple of the Universe at 28, accidentally built Medical Manager software in his 30s, company acquired for $5B at 55, first book The Untethered Soul at 60, Oprah appearance at 65, 5M+ copies sold by 79.","keyDecision":"Followed the principle of surrender so completely that he said yes to building a software company he never planned, then walked away from the wealth to keep teaching meditation.","scaleModel":"Books create global reach, the podcast extends teachings weekly, Temple of the Universe provides the anchor community.","lessonsForUser":"If you teach and care about inner freedom: write one book that says the thing clearly, then spend the rest of your life being the proof."},"confidence":"high"},
  {"name":"Michael Beckwith","source":"non-founder","domain":"spiritual leadership / visioning / New Thought ministry","oneLiner":"Grew a living room prayer group into a 9,000-person weekly congregation that Oprah called her spiritual home.","primaryProblem":"forgot_what_for","primarySkills":["coaching","performing","leading"],"careerModel":{"type":"spiritual_community_and_training","primaryRevenue":"Agape community offerings and Life Visioning courses","revenueStreams":["community tithes and donations","Life Visioning courses","book royalties","speaking engagements","online courses","practitioner training programme"],"trajectory":"Inner vision at 27, founded Agape in a living room at 30, grew to 9,000 weekly members, featured in The Secret at 50, TED talk at 58, Life Visioning on Mindvalley reaching millions by 69.","keyDecision":"Kept Agape trans-denominational from day one, refusing to affiliate with any single religion.","scaleModel":"Weekly services build a loyal congregation, The Secret gave global visibility, licensed courses on Mindvalley extend reach, 365 trained practitioners deliver healing without him present.","lessonsForUser":"If you lead and care about spiritual growth: build a physical community first, develop your signature process, then license it to platforms that already have the audience."},"confidence":"high"},
  {"name":"Radha Agrawal","source":"non-founder","domain":"community building / sober movement / belonging","oneLiner":"Proved that the most radical party you can throw starts at 6am, sober, with a thousand strangers dancing together.","primaryProblem":"left_behind","primarySkills":["connecting","creating","leading"],"careerModel":{"type":"community_movement_and_licensing","primaryRevenue":"Daybreaker event tickets and brand partnerships","revenueStreams":["event tickets","brand partnerships","book royalties","speaking engagements","city licensing"],"trajectory":"Investment banking analyst at 22, left finance for creative directing at 23, co-founded THINX at 29, launched first Daybreaker at 34, grew to 1M+ community across 30+ cities by 47, sold-out Oprah arena tour at 41.","keyDecision":"After losing one company to a hostile takeover, chose to build Daybreaker as a community-first movement rather than a venture-backed startup.","scaleModel":"City-by-city licensing model where local leaders host Daybreaker events under the brand, allowing global expansion without centralised operations.","lessonsForUser":"If you connect and care about community: start one unforgettable event in one city, make it so good people beg to bring it to theirs, then license the format."},"confidence":"high"},
  {"name":"Meghan Pappenheim","source":"non-founder","domain":"wellness festivals / yoga community / social entrepreneurship","oneLiner":"Built the world's most beloved yoga festival by treating Bali like a village that needed a town square, not a brand.","primaryProblem":"left_behind","primarySkills":["connecting","building","leading"],"careerModel":{"type":"community_ecosystem_builder","primaryRevenue":"Festival ticket sales and Yoga Barn class fees","revenueStreams":["festival ticket sales","yoga studio class fees","wellness retreats","restaurant revenue","community directory listings"],"trajectory":"First business selling seedlings at 9, first yoga class at 13 in NYC, moved to Bali at 20, launched BaliSpirit online directory at 31, opened The Yoga Barn at 35, pulled together the first BaliSpirit Festival in 3 months at 36, grew it to 7,000 attendees across 50 countries.","keyDecision":"Built the community infrastructure first (directory, yoga studio, cafes) so the festival had a village to grow from, not just an audience to sell to.","scaleModel":"Physical community hub (Yoga Barn with 25+ daily classes) anchors a festival that draws 7,000 people annually, creating a self-sustaining wellness ecosystem.","lessonsForUser":"If you connect and care about community: build the daily gathering place first, then the festival becomes a celebration of what already exists."},"confidence":"high"},
  {"name":"Jeff Krasno","source":"non-founder","domain":"wellness events / online learning / mindful living","oneLiner":"Took everything he knew about filling music venues and pointed it at yoga mats instead.","primaryProblem":"forgot_what_for","primarySkills":["building","connecting","leading"],"careerModel":{"type":"events_to_platform_pivot","primaryRevenue":"Commune online membership and retreat centre","revenueStreams":["festival ticket sales","online course subscriptions","retreat centre bookings","podcast sponsorships","book royalties"],"trajectory":"Columbia grad at 23, co-founded Velour record label at 29, built Wanderlust yoga festival at 39 to 68 events in 20 countries, exited at 48, co-founded Commune online platform at 48, grew newsletter to 1M+ subscribers, built 10-acre Topanga retreat centre.","keyDecision":"Exited Wanderlust at its peak to build Commune, betting that the future of wellness was daily digital practice, not annual festival peaks.","scaleModel":"Live festival brand built global awareness, then pivoted to online platform with expert-led courses, weekly newsletter to 1M+ readers, and a physical retreat lab.","lessonsForUser":"If you build events and care about wellness: use festivals to learn what your community actually needs, then build the daily product they will use between events."},"confidence":"high"},
  {"name":"Gabrielle Roth","source":"non-founder","domain":"conscious dance / movement as meditation / ecstatic dance","oneLiner":"Proved that the fastest way to stillness is to dance until your ego gives up.","primaryProblem":"voice_taken","primarySkills":["performing","creating","teaching"],"careerModel":{"type":"method_certification_empire","primaryRevenue":"Teacher certification and workshop fees","revenueStreams":["teacher certification programme","workshop fees","book royalties","music album sales (Raven Recording)","retreat fees"],"trajectory":"Told she would never dance again after a knee injury, healed through movement at Esalen, Fritz Perls asked her to teach dance at 26, designed the 5Rhythms Wave in the late 1970s, founded The Moving Center in NYC at 36, certified 300+ teachers in 50+ countries by her death at 71.","keyDecision":"Mapped dance onto a repeatable five-stage structure so anyone could facilitate it, not just gifted dancers.","scaleModel":"Created a codified method, trained teachers through rigorous 2-year certification, and produced her own music through Raven Recording to soundtrack the practice worldwide.","lessonsForUser":"If you create movement practices and care about healing: codify the structure so others can teach it, then produce the soundtrack so the experience stays consistent everywhere."},"confidence":"high"},
  {"name":"Larry Harvey","source":"non-founder","domain":"participatory art / counter-culture community / radical self-expression","oneLiner":"Burned a wooden man on a beach and accidentally started a civilisation.","primaryProblem":"life_not_yours","primarySkills":["leading","designing","connecting"],"careerModel":{"type":"community_to_nonprofit_movement","primaryRevenue":"Event ticket sales (Black Rock City)","revenueStreams":["festival ticket sales","art grants programme","regional event licensing","merchandise"],"trajectory":"Failed landscaper in Portland, burned an 8-foot effigy on Baker Beach with a friend at 38, grew the gathering from 20 people to 800 in four years, moved to Black Rock Desert at 42, wrote the 10 Principles at 56, transitioned to nonprofit at 65, 80,000 participants and regional burns in 34 countries by his death at 70.","keyDecision":"Wrote 10 Principles in 2004 as guidelines for regional burns, giving the culture a codified value system that could replicate without him.","scaleModel":"A single annual gathering built cultural identity, the 10 Principles codified it, regional burns replicated it in 34 countries, and nonprofit status ensured it would outlive the founder.","lessonsForUser":"If you lead and care about culture: build the gathering first, then write the principles so the culture can spread without needing you in the room."},"confidence":"high"}
];

const dnaEntries = [
  {name:"Vishen Lakhiani",experienceType:"cohort",workRhythm:4,fuelType:3,knowledgeStyle:4,impactStyle:5,growthMode:5,confidence:88},
  {name:"Michael Singer",experienceType:"book_newsletter",workRhythm:1,fuelType:1,knowledgeStyle:4,impactStyle:2,growthMode:1,confidence:90},
  {name:"Michael Beckwith",experienceType:"live_events",workRhythm:2,fuelType:3,knowledgeStyle:5,impactStyle:4,growthMode:3,confidence:87},
  {name:"Radha Agrawal",experienceType:"live_events",workRhythm:4,fuelType:3,knowledgeStyle:5,impactStyle:4,growthMode:4,confidence:85},
  {name:"Meghan Pappenheim",experienceType:"live_events",workRhythm:2,fuelType:1,knowledgeStyle:4,impactStyle:4,growthMode:4,confidence:82},
  {name:"Jeff Krasno",experienceType:"live_events",workRhythm:4,fuelType:1,knowledgeStyle:3,impactStyle:4,growthMode:5,confidence:85},
  {name:"Gabrielle Roth",experienceType:"facilitation",workRhythm:2,fuelType:3,knowledgeStyle:5,impactStyle:3,growthMode:2,confidence:90},
  {name:"Larry Harvey",experienceType:"facilitation",workRhythm:2,fuelType:3,knowledgeStyle:5,impactStyle:5,growthMode:4,confidence:88}
];

const offerMapEntries = {
  "Vishen Lakhiani":{"attraction":["free masterclasses","books"],"core":["membership subscriptions","cohort-based Quests"],"scale":["coaching certifications","live festivals (A-Fest, Mindvalley University)"],"continuity":["premium coaching","app subscriptions"]},
  "Michael Singer":{"attraction":["podcast","free Temple of the Universe talks"],"core":["book royalties"],"scale":["online courses","speaking engagements"],"continuity":["podcast","community donations"]},
  "Michael Beckwith":{"attraction":["book royalties","free weekly livestreams"],"core":["weekly Agape services","speaking engagements"],"scale":["Life Visioning courses (Mindvalley, Shift Network)","practitioner training programme"],"continuity":["online courses","community tithes and donations"]},
  "Radha Agrawal":{"attraction":["book royalties (Belong)","free community events"],"core":["Daybreaker event tickets","brand partnerships"],"scale":["city licensing/expansion","speaking engagements"],"continuity":["Daybreaker membership community"]},
  "Meghan Pappenheim":{"attraction":["community directory listings","nonprofit outreach programs"],"core":["festival ticket sales","yoga studio class fees"],"scale":["Portugal Spirit Festival expansion","wellness retreat programming"],"continuity":["restaurant revenue","Yoga Barn memberships"]},
  "Jeff Krasno":{"attraction":["book royalties","weekly newsletter (Commusings)"],"core":["Commune online course subscriptions","Topanga retreat bookings"],"scale":["Wanderlust festival events"],"continuity":["podcast sponsorships","Commune membership"]},
  "Gabrielle Roth":{"attraction":["book royalties","music album sales (Raven Recording)"],"core":["workshop fees","retreat fees"],"scale":["teacher certification programme"],"continuity":["music catalogue royalties (16 albums)","ongoing teacher certification renewals"]},
  "Larry Harvey":{"attraction":["regional burns (34 countries)"],"core":["Black Rock City ticket sales"],"scale":["10 Principles framework licensing to regional network","art grants programme"],"continuity":["Burning Man Project nonprofit donations","merchandise"]}
};

const gsEntries = {
  "Vishen Lakhiani":{"name":"Vishen Lakhiani","early_growth":"Started as a meditation teacher selling other people's courses online from a Starbucks in New York. Used Google Ads and email marketing to build an audience before creating his own content.","scaling_move":"Published The Code of the Extraordinary Mind in 2016, which hit the NYT bestseller list and transformed Mindvalley from a scrappy startup into a mainstream brand.","current_model":"Membership platform with 100+ Quests from curated teachers, coaching certifications, live festivals, and a premium coaching tier.","growth_category":"one_project","first_step":"Curate and sell other teachers' best content online before creating your own.","remarkable_thing":"A broke engineer who built a $100M consciousness university from a Starbucks without taking a single dollar of outside funding.","trust_behavior":"Bootstrapped for 14 years selling other people's courses before writing his own book.","remarkable_category":"origin_story","remarkable_type":"bootstrap origin","remarkable_trigger":"radical_consistency","remarkable_behavior":"A computer engineer who spent 14 years bootstrapping a personal growth company from $700 to $100M without investors."},
  "Michael Singer":{"name":"Michael Singer","early_growth":"Had a spiritual awakening at 24 and went into seclusion in the woods of Alachua, Florida. Founded Temple of the Universe in 1975 as a free meditation centre open to anyone.","scaling_move":"Published The Untethered Soul in 2007, which spent years growing by word of mouth before exploding after his 2012 Oprah Super Soul Sunday appearance.","current_model":"Books provide global reach, The Michael Singer Podcast extends weekly teachings, Temple of the Universe remains the in-person anchor.","growth_category":"free_events","first_step":"Start a free weekly meditation or discussion group and commit to showing up for years.","remarkable_thing":"A meditator hiding in the Florida woods who accidentally built a billion-dollar software company by saying yes to whatever life brought.","trust_behavior":"Taught free meditation at Temple of the Universe for 32 years before publishing his first book.","remarkable_category":"opposite_method","remarkable_type":"accidental empire","remarkable_trigger":"unexpected_origin","remarkable_behavior":"A reclusive meditator who said yes to every opportunity and accidentally built a $5B software company while living in the woods."},
  "Michael Beckwith":{"name":"Michael Beckwith","early_growth":"Started Agape in 1986 with a small prayer group in his living room in Los Angeles. Grew through word of mouth and weekly consistency.","scaling_move":"Featured as a teacher in The Secret (2006), which brought global visibility and millions of new followers overnight.","current_model":"Weekly services at Agape anchor the community, Life Visioning courses on Mindvalley and Shift Network reach global audiences, 365 trained practitioners extend his healing work.","growth_category":"free_events","first_step":"Start a free weekly prayer or visioning circle in your living room and show up every single week.","remarkable_thing":"A man who turned a living room prayer group into a 9,000-person spiritual community that became Oprah's favourite church.","trust_behavior":"Led free weekly services for 20 years before appearing in The Secret or teaching on any platform.","remarkable_category":"origin_story","remarkable_type":"living room to megachurch","remarkable_trigger":"radical_consistency","remarkable_behavior":"A spiritual teacher who showed up every Sunday for 20 years until 9,000 people were showing up with him."},
  "Radha Agrawal":{"name":"Radha Agrawal","early_growth":"After losing her company to a hostile takeover, threw a sober morning dance party in a warehouse in Union Square, New York, in December 2013. Word of mouth filled the next one.","scaling_move":"Licensed the Daybreaker format to local hosts in other cities, growing from one New York event to 30+ cities across seven continents.","current_model":"City-licensed Daybreaker events globally, brand partnerships, book and speaking revenue, Oprah arena tour partnership.","growth_category":"free_events","first_step":"Throw one unforgettable morning event for 50 people and make it so good they tell everyone.","remarkable_thing":"A woman who lost her company to a hostile takeover and responded by throwing a sober dance party at 6am that became a million-person global movement.","trust_behavior":"Danced alongside strangers at every Daybreaker event for years before scaling or writing a book.","remarkable_category":"origin_story","remarkable_type":"comeback movement","remarkable_trigger":"unexpected_origin","remarkable_behavior":"An entrepreneur who lost everything and responded by throwing a sober 6am dance party that grew into a million-person community."},
  "Meghan Pappenheim":{"name":"Meghan Pappenheim","early_growth":"Moved to Bali at 20, built an online community directory for socially conscious businesses in Ubud, then opened The Yoga Barn in 2007 with just two studios and four classes a day.","scaling_move":"Pulled together the first BaliSpirit Festival in three months in 2008, turning the existing yoga and wellness community into an annual 7,000-person gathering.","current_model":"The Yoga Barn runs 25+ classes daily as the year-round anchor, the BaliSpirit Festival draws thousands annually, and the ecosystem includes restaurants, galleries, and nonprofits.","growth_category":"grassroots","first_step":"Create a community directory or gathering point for the wellness practitioners already around you.","remarkable_thing":"A 20-year-old New Yorker who moved to Bali and built the world's most beloved yoga festival by planting a village first.","trust_behavior":"Built an online community directory and opened a small yoga studio years before attempting a festival.","remarkable_category":"origin_story","remarkable_type":"outsider who became the centre","remarkable_trigger":"radical_consistency","remarkable_behavior":"A New Yorker who arrived in Bali at 20 and spent 15 years building community infrastructure before the festival became world-famous."},
  "Jeff Krasno":{"name":"Jeff Krasno","early_growth":"Co-founded Velour Recordings, a record label in NYC at 29. After witnessing his wife's yoga retreats in Costa Rica, combined event production skills with wellness to launch Wanderlust Festival in 2009.","scaling_move":"Grew Wanderlust to 68 events in 20 countries with 120,000 annual tickets sold, becoming the world's most recognised wellness events brand.","current_model":"Exited Wanderlust in 2018 to co-found Commune, an online learning platform. Writes a weekly essay to 1M+ subscribers. Runs Commune Topanga, a 10-acre retreat centre.","growth_category":"one_project","first_step":"Combine two skills you already have into a single weekend experience for 50 people.","remarkable_thing":"A music industry guy who looked at a yoga mat and saw a festival stage.","trust_behavior":"Ran a record label and produced music events for a decade before applying those skills to wellness.","remarkable_category":"origin_story","remarkable_type":"cross-pollination","remarkable_trigger":"unexpected_origin","remarkable_behavior":"A record label founder who watched his wife's yoga retreat and realised he could produce wellness the way he produced concerts."},
  "Gabrielle Roth":{"name":"Gabrielle Roth","early_growth":"After a knee injury ended her dance career, she retreated to Esalen where Fritz Perls asked her to teach dance. Spent a decade experimenting with movement as therapy.","scaling_move":"Founded The Moving Center in New York in 1977 and began a rigorous 2-year teacher certification programme in 1988.","current_model":"300+ certified teachers in 50+ countries carry the 5Rhythms method worldwide. Raven Recording catalogue of 16 albums soundtracks classes globally. Her son Jonathan Horan directs the organisation.","growth_category":"one_project","first_step":"Put on music and move until your body finds its own pattern. Then invite five people to do it with you.","remarkable_thing":"A dancer told she would never dance again who turned her recovery into a global movement practice.","trust_behavior":"Spent over a decade dancing and teaching at Esalen, Kripalu, and Omega before formalising the certification.","remarkable_category":"impossible_proof","remarkable_type":"injury to invention","remarkable_trigger":"vulnerability_as_strength","remarkable_behavior":"A dancer told she would never dance again who healed through movement and turned the process into a method practiced in 50+ countries."},
  "Larry Harvey":{"name":"Larry Harvey","early_growth":"A struggling landscaper in Portland, he burned an 8-foot wooden man on Baker Beach in San Francisco in 1986 with friend Jerry James and about 20 people.","scaling_move":"Moved the event to the Black Rock Desert in 1990, giving it unlimited space to grow. Attendance doubled annually through the 1990s.","current_model":"Black Rock City draws 80,000 participants annually. Regional events in 34 countries. Burning Man Project operates as a nonprofit. The 10 Principles guide 235+ regional contacts worldwide.","growth_category":"grassroots","first_step":"Build something with your hands, burn it in front of friends, and see what happens to the group.","remarkable_thing":"A failed landscaper who burned a stick figure on a beach and accidentally built a civilisation with its own constitution.","trust_behavior":"Burned the Man every year for 18 years before writing any formal principles or organisational structure.","remarkable_category":"origin_story","remarkable_type":"accidental founder","remarkable_trigger":"stupid_simplicity","remarkable_behavior":"A landscaper who burned an 8-foot wooden man on a beach in 1986 and kept showing up until 80,000 people did too."}
};

const psEntries = [
  {name:"Vishen Lakhiani",dominantCategories:["leading","teaching","building"],playSkills:[{category:"leading",skill:"Build a stage for other people's genius",confidence:"high",evidence:"Curated 100+ Quests from world-class teachers on Mindvalley's platform, reaching 20M+ students globally"},{category:"teaching",skill:"Turn ancient practices into modern cohorts",confidence:"high",evidence:"Created the Quest format, 35-day structured learning journeys that made meditation and consciousness work feel like a course"},{category:"building",skill:"Bootstrap a movement without outside money",confidence:"high",evidence:"Grew Mindvalley from $700 to $100M revenue with zero venture capital over two decades"},{category:"performing",skill:"Command a room of 10,000",confidence:"high",evidence:"Keynote speaker at major stages worldwide, hosts Mindvalley events with thousands of live attendees"}],antiTags:[{category:"coaching",skill:"Work deeply with individual clients",evidence:"Operates at platform scale, not 1:1"}]},
  {name:"Michael Singer",dominantCategories:["teaching","storytelling"],playSkills:[{category:"teaching",skill:"Reduce complex theory to one question",confidence:"high",evidence:"Distilled decades of meditation into 'Who is the one noticing?', reaching 5M+ readers"},{category:"storytelling",skill:"Turn your life into the textbook",confidence:"high",evidence:"The Surrender Experiment used his accidental billion-dollar career as the case study for spiritual surrender"},{category:"coaching",skill:"Hold space for decades without burning out",confidence:"high",evidence:"Has led free weekly meditation at Temple of the Universe since 1975, over 50 years"},{category:"teaching",skill:"Make sitting still feel like the bravest act",confidence:"high",evidence:"Convinced millions that doing nothing with their thoughts was harder and more rewarding than any achievement"}],antiTags:[{category:"performing",skill:"Command a room of 10,000",evidence:"Avoids large-scale performances and media. Teaches in small settings by design."}]},
  {name:"Michael Beckwith",dominantCategories:["coaching","performing","leading"],playSkills:[{category:"performing",skill:"Channel spiritual energy on stage",confidence:"high",evidence:"Delivers weekly sermons to 9,000+ congregation at Agape and speaks at global events including TED"},{category:"coaching",skill:"Codify a practice into a teachable method",confidence:"high",evidence:"Created the Life Visioning Process, now taught on Mindvalley and through Agape's Practitioner Programme"},{category:"leading",skill:"Build a congregation from nothing",confidence:"high",evidence:"Grew Agape from a living room prayer group in 1986 to 9,000+ weekly attendees"},{category:"connecting",skill:"Build community through consistency",confidence:"high",evidence:"Co-founded the Association for Global New Thought, co-chaired the Season for Nonviolence"},{category:"teaching",skill:"Translate ancient wisdom for modern ears",confidence:"high",evidence:"Three Nautilus Award-winning books bridging Eastern and Western spiritual traditions"}],antiTags:[{category:"building",skill:"Build technology or digital products",evidence:"Does not build tech. Licenses his method to platforms like Mindvalley."}]},
  {name:"Radha Agrawal",dominantCategories:["connecting","creating","leading"],playSkills:[{category:"connecting",skill:"Turn strangers into a tribe before breakfast",confidence:"high",evidence:"Daybreaker morning dance events have brought together 1M+ people across 30+ cities on seven continents"},{category:"creating",skill:"Design an experience so good people license it",confidence:"high",evidence:"Daybreaker's format was licensed city-by-city to local hosts, scaling globally"},{category:"leading",skill:"Rally a group behind an idea",confidence:"high",evidence:"Led sold-out Oprah Winfrey arena tour, moving 155,000 people through dance and motivation"},{category:"storytelling",skill:"Turn personal crisis into collective awakening",confidence:"high",evidence:"Lost Super Sprowtz to a hostile takeover, then channelled the grief into founding Daybreaker and writing Belong"}],antiTags:[{category:"teaching",skill:"Teach through courses or certifications",evidence:"Does not teach through curricula. Builds experiences, not courses."}]},
  {name:"Meghan Pappenheim",dominantCategories:["connecting","building","leading"],playSkills:[{category:"connecting",skill:"Build community through consistency",confidence:"high",evidence:"Grew The Yoga Barn from 4 classes a day in 2007 to 25+ daily classes"},{category:"building",skill:"Build the village before the festival",confidence:"high",evidence:"Created BaliSpirit directory, Yoga Barn, cafes, and galleries before launching the festival"},{category:"leading",skill:"Rally a group behind an idea",confidence:"high",evidence:"Pulled together the first BaliSpirit Festival in just three months"},{category:"connecting",skill:"Turn a place into a pilgrimage",confidence:"high",evidence:"Made Ubud a global wellness destination drawing 7,000 festival attendees from 50+ countries"}],antiTags:[{category:"performing",skill:"Command a room of 10,000",evidence:"Builds platforms for others to shine, not herself. She calls herself 'Chief Manifestation Officer,' not headliner."}]},
  {name:"Jeff Krasno",dominantCategories:["building","connecting","leading"],playSkills:[{category:"building",skill:"Cross-pollinate two industries into one",confidence:"high",evidence:"Combined music event production with yoga to create Wanderlust, 68 events in 20 countries"},{category:"connecting",skill:"Build community through consistency",confidence:"high",evidence:"Writes Commusings, a personal weekly essay, to over 1 million subscribers every Sunday"},{category:"leading",skill:"Know when to exit and rebuild",confidence:"high",evidence:"Left Wanderlust at its peak in 2018 to co-found Commune, pivoting from festivals to daily digital practice"},{category:"connecting",skill:"Turn curiosity into consistent content",confidence:"high",evidence:"Hosts the Commune podcast weekly, interviewing scientists, spiritual leaders, and storytellers"}],antiTags:[{category:"coaching",skill:"Coach someone through a block",evidence:"Krasno is a producer and platform builder, not a practitioner. He curates experts to teach."}]},
  {name:"Gabrielle Roth",dominantCategories:["performing","creating","teaching"],playSkills:[{category:"performing",skill:"Teach through the body, not the mind",confidence:"high",evidence:"Created 5Rhythms as a body-first path to stillness, now practiced in 50+ countries"},{category:"creating",skill:"Codify a practice into a teachable method",confidence:"high",evidence:"Mapped free-form dance onto a repeatable 5-stage Wave, enabling a 2-year certification producing 300+ teachers"},{category:"teaching",skill:"Certify others to carry your method",confidence:"high",evidence:"Built rigorous teacher training selecting 40-50 dancers per cycle, growing to 396 certified teachers"},{category:"performing",skill:"Turn personal crisis into collective awakening",confidence:"high",evidence:"Transformed a career-ending knee injury into the origin of 5Rhythms"}],antiTags:[{category:"teaching",skill:"Break down a hard idea so anyone gets it",evidence:"Deliberately refused to intellectualise her method. She taught through sweat, not explanation."}]},
  {name:"Larry Harvey",dominantCategories:["leading","designing","connecting"],playSkills:[{category:"leading",skill:"Write the rules so the culture can travel",confidence:"high",evidence:"Authored the 10 Principles in 2004, enabling 235+ regional contacts to replicate the culture across 34 countries"},{category:"designing",skill:"Design a container, not a programme",confidence:"high",evidence:"Created Black Rock City as a blank canvas where 80,000 participants build their own experience"},{category:"connecting",skill:"Build community through consistency",confidence:"high",evidence:"Burned the Man every single year from 1986 until his death in 2018, 32 consecutive years"},{category:"leading",skill:"Build something that outlives you",confidence:"high",evidence:"Transitioned Burning Man to nonprofit in 2013, designing for a hundred-year movement"}],antiTags:[{category:"teaching",skill:"Codify a practice into a teachable method",evidence:"Deliberately refused to create curriculum or training. The 10 Principles are values, not instructions."}]}
];

// ─── INSERT ───────────────────────────────────────────────────────

const cm = JSON.parse(fs.readFileSync(DATA+'/careerModels.json','utf8'));
cmEntries.forEach(e => { if (!cm.profiles.find(p=>p.name===e.name)) cm.profiles.push(e); });
cm.meta.totalProfiles = cm.profiles.filter(p=>p.careerModel).length;
cm.meta.totalPeople = cm.profiles.length;
fs.writeFileSync(DATA+'/careerModels.json', JSON.stringify(cm,null,2));
console.log('CM: '+cm.profiles.length);

const dna = JSON.parse(fs.readFileSync(DATA+'/experienceCreatorDNA.json','utf8'));
dnaEntries.forEach(e => { if (!dna.profiles.find(p=>p.name===e.name)) dna.profiles.push(e); });
dna.meta.totalProfiles = dna.profiles.length;
fs.writeFileSync(DATA+'/experienceCreatorDNA.json', JSON.stringify(dna,null,2));
console.log('DNA: '+dna.profiles.length);

const om = JSON.parse(fs.readFileSync(DATA+'/experienceCreatorOfferMap.json','utf8'));
Object.entries(offerMapEntries).forEach(([k,v]) => { if (!om.creators[k]) om.creators[k] = v; });
om.meta.totalCreators = Object.keys(om.creators).length;
fs.writeFileSync(DATA+'/experienceCreatorOfferMap.json', JSON.stringify(om,null,2));
console.log('OM: '+om.meta.totalCreators);

const gs = JSON.parse(fs.readFileSync(DATA+'/experienceCreatorGrowthStrategies.json','utf8'));
Object.entries(gsEntries).forEach(([k,v]) => { if (!gs.creators[k]) gs.creators[k] = v; });
if (gs.meta) gs.meta.count = Object.keys(gs.creators).length;
fs.writeFileSync(DATA+'/experienceCreatorGrowthStrategies.json', JSON.stringify(gs,null,2));
console.log('GS: '+Object.keys(gs.creators).length);

const ps = JSON.parse(fs.readFileSync(DATA+'/nonFounderPlaySkills.json','utf8'));
psEntries.forEach(e => { if (!ps.profiles.find(p=>p.name===e.name)) ps.profiles.push(e); });
ps.meta.totalProfiles = ps.profiles.length;
fs.writeFileSync(DATA+'/nonFounderPlaySkills.json', JSON.stringify(ps,null,2));
console.log('PS: '+ps.profiles.length);

console.log('\nAll 8 inserted!');
