/**
 * Step8_GrandSlam - Final Grand Slam Score and Stack Slide
 *
 * Features:
 * - Visual Grand Slam Score with value equation breakdown
 * - Stack Slide showing complete offer with bonuses
 * - Copy/download options
 * - Save to database
 */

import { useState, useEffect, useRef } from 'react'
import { supabase } from '../../../lib/supabaseClient'
import { useAuth } from '../../../auth/AuthProvider'

function Step8_GrandSlam({ offerData, selectedVersion, score, onComplete, setIsLoading, setError }) {
  const { user } = useAuth()
  const stackSlideRef = useRef(null)
  const [isSaving, setIsSaving] = useState(false)
  const [isSaved, setIsSaved] = useState(false)
  const [copySuccess, setCopySuccess] = useState(false)

  const { versions, bonuses, dreamOutcome, bucket, proofAnalysis, speedAnalysis, easeAnalysis } = offerData
  const versionData = versions?.[selectedVersion]
  const versionBonuses = bonuses?.[selectedVersion] || []

  const versionLabels = {
    product: { icon: '📦', name: 'Product', color: '#3b82f6' },
    service: { icon: '🤝', name: 'Service', color: '#8b5cf6' },
    hybrid: { icon: '🎓', name: 'Hybrid', color: '#ec4899' }
  }

  const label = versionLabels[selectedVersion]

  // Calculate total value
  const coreValue = versionData?.suggestedPrice || 0
  const bonusValue = versionBonuses.reduce((sum, b) => sum + (b.perceivedValue || 0), 0)
  const totalValue = coreValue + bonusValue

  // Save to database
  const handleSave = async () => {
    if (!user) return

    setIsSaving(true)
    try {
      const offerRecord = {
        user_id: user.id,
        dream_outcome: dreamOutcome,
        bucket: bucket,
        selected_version: selectedVersion,
        version_name: versionData?.name,
        version_data: versionData,
        bonuses: versionBonuses,
        grand_slam_score: score?.total,
        grade: score?.grade?.letter,
        proof_score: score?.proofScore,
        speed_score: score?.speedScore,
        ease_score: score?.easeScore,
        core_price: coreValue,
        bonus_value: bonusValue,
        total_value: totalValue,
        proof_analysis: proofAnalysis?.[selectedVersion],
        speed_analysis: speedAnalysis?.[selectedVersion],
        ease_analysis: easeAnalysis?.[selectedVersion],
        status: 'completed',
        completed_at: new Date().toISOString()
      }

      const { error } = await supabase
        .from('offer_creations')
        .upsert(offerRecord, { onConflict: 'user_id' })

      if (error) throw error

      setIsSaved(true)
    } catch (err) {
      console.error('Error saving offer:', err)
      setError('Failed to save offer. Please try again.')
    } finally {
      setIsSaving(false)
    }
  }

  // Copy stack slide as text
  const handleCopy = async () => {
    const text = generateStackSlideText()
    try {
      await navigator.clipboard.writeText(text)
      setCopySuccess(true)
      setTimeout(() => setCopySuccess(false), 2000)
    } catch (err) {
      console.error('Copy failed:', err)
      setError('Failed to copy to clipboard')
    }
  }

  // Generate text version of stack slide
  const generateStackSlideText = () => {
    let text = `🎯 GRAND SLAM OFFER: ${versionData?.name}\n`
    text += `━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n`

    text += `🌟 DREAM OUTCOME:\n${dreamOutcome}\n\n`

    text += `📦 WHAT YOU GET:\n`
    versionData?.deliverables?.forEach((item, i) => {
      text += `${i + 1}. ${item}\n`
    })
    text += `\n`

    text += `🎁 BONUSES:\n`
    versionBonuses.forEach((bonus, i) => {
      text += `${i + 1}. ${bonus.name} (Value: $${bonus.perceivedValue})\n`
      text += `   ${bonus.description}\n`
    })
    text += `\n`

    text += `💰 VALUE BREAKDOWN:\n`
    text += `Core Offer: $${coreValue.toLocaleString()}\n`
    text += `Bonus Stack: $${bonusValue.toLocaleString()}\n`
    text += `TOTAL VALUE: $${totalValue.toLocaleString()}\n\n`

    text += `📊 GRAND SLAM SCORE: ${score?.total}/100 (${score?.grade?.letter})\n`
    text += `━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n`
    text += `Generated by Flow Academy's $100M Offer Builder\n`

    return text
  }

  // Auto-save on mount
  useEffect(() => {
    if (!isSaved && user) {
      handleSave()
    }
  }, [])

  return (
    <div className="grand-slam-step">
      <div className="question-header">
        <span className="step-label">Step 8 of 8 - Complete!</span>
        <h2>Your Grand Slam Offer</h2>
      </div>

      {/* Grand Slam Score Display */}
      <div className="grand-slam-score" style={{ borderColor: score?.grade?.color }}>
        <div className="score-circle" style={{ background: `linear-gradient(135deg, ${score?.grade?.color}22, ${score?.grade?.color}44)` }}>
          <div className="score-number" style={{ color: score?.grade?.color }}>{score?.total}</div>
          <div className="score-max">/100</div>
        </div>
        <div className="score-info">
          <div className="grade-badge" style={{ background: score?.grade?.color }}>
            {score?.grade?.letter}
          </div>
          <div className="grade-label">{score?.grade?.label}</div>
        </div>
      </div>

      {/* Value Equation Breakdown */}
      <div className="value-equation">
        <div className="equation-header">
          <span className="equation-icon">📐</span>
          <span>Hormozi Value Equation</span>
        </div>
        <div className="equation-formula">
          <div className="equation-numerator">
            <div className="factor">
              <span className="factor-label">Dream Outcome</span>
              <span className="factor-value">✓</span>
            </div>
            <span className="operator">×</span>
            <div className="factor">
              <span className="factor-label">Perceived Likelihood</span>
              <span className="factor-value">{score?.proofScore}/10</span>
            </div>
          </div>
          <div className="equation-divider">÷</div>
          <div className="equation-denominator">
            <div className="factor">
              <span className="factor-label">Time Delay</span>
              <span className="factor-value">{10 - score?.speedScore}/10</span>
            </div>
            <span className="operator">×</span>
            <div className="factor">
              <span className="factor-label">Effort & Sacrifice</span>
              <span className="factor-value">{10 - score?.easeScore}/10</span>
            </div>
          </div>
        </div>
      </div>

      {/* Stack Slide */}
      <div className="stack-slide" ref={stackSlideRef}>
        <div className="stack-header" style={{ background: label.color }}>
          <span className="stack-icon">{label.icon}</span>
          <h3>{versionData?.name}</h3>
          <span className="stack-type">{label.name} Offer</span>
        </div>

        {/* Dream Outcome */}
        <div className="stack-section dream-section">
          <div className="section-label">🌟 DREAM OUTCOME</div>
          <p className="dream-text">"{dreamOutcome}"</p>
        </div>

        {/* Core Deliverables */}
        <div className="stack-section deliverables-section">
          <div className="section-label">📦 WHAT'S INCLUDED</div>
          <ul className="deliverables-list">
            {versionData?.deliverables?.map((item, i) => (
              <li key={i}>{item}</li>
            ))}
          </ul>
          <div className="section-value">
            <span className="value-label">Core Value:</span>
            <span className="value-amount">${coreValue.toLocaleString()}</span>
          </div>
        </div>

        {/* Bonus Stack */}
        <div className="stack-section bonus-section">
          <div className="section-label">🎁 BONUS STACK</div>
          <div className="bonus-list">
            {versionBonuses.map((bonus, i) => (
              <div key={i} className="bonus-item">
                <div className="bonus-header">
                  <span className="bonus-name">{bonus.name}</span>
                  <span className="bonus-value">${bonus.perceivedValue}</span>
                </div>
                <p className="bonus-desc">{bonus.description}</p>
              </div>
            ))}
          </div>
          <div className="section-value">
            <span className="value-label">Bonus Value:</span>
            <span className="value-amount">${bonusValue.toLocaleString()}</span>
          </div>
        </div>

        {/* Total Value */}
        <div className="stack-section total-section" style={{ borderColor: label.color }}>
          <div className="total-value">
            <span className="total-label">TOTAL VALUE:</span>
            <span className="total-amount">${totalValue.toLocaleString()}</span>
          </div>
          <div className="price-today">
            <span className="price-label">Your Investment Today:</span>
            <span className="price-amount">${coreValue.toLocaleString()}</span>
          </div>
        </div>

        {/* Speed & Ease Highlights */}
        <div className="stack-section highlights-section">
          <div className="highlight">
            <span className="highlight-icon">⚡</span>
            <span className="highlight-text">
              {speedAnalysis?.[selectedVersion]?.marketingAngle || 'Get results faster'}
            </span>
          </div>
          <div className="highlight">
            <span className="highlight-icon">🎯</span>
            <span className="highlight-text">
              {easeAnalysis?.[selectedVersion]?.marketingCopy?.split('\n')[0] || 'Easy to implement'}
            </span>
          </div>
        </div>
      </div>

      {/* Action Buttons */}
      <div className="action-buttons">
        <button
          className="action-btn copy-btn"
          onClick={handleCopy}
          disabled={copySuccess}
        >
          {copySuccess ? '✓ Copied!' : '📋 Copy as Text'}
        </button>

        <button
          className="action-btn save-btn"
          onClick={handleSave}
          disabled={isSaving || isSaved}
        >
          {isSaved ? '✓ Saved' : isSaving ? 'Saving...' : '💾 Save Offer'}
        </button>
      </div>

      {/* Next Steps */}
      <div className="next-steps">
        <h4>What's Next?</h4>
        <div className="next-steps-list">
          <div className="next-step">
            <span className="step-num">1</span>
            <span className="step-text">Create your lead magnet to attract prospects</span>
          </div>
          <div className="next-step">
            <span className="step-num">2</span>
            <span className="step-text">Build your funnel to nurture and convert</span>
          </div>
          <div className="next-step">
            <span className="step-num">3</span>
            <span className="step-text">Launch and track with the Funnel Calculator</span>
          </div>
        </div>
      </div>

      <button className="primary-button" onClick={onComplete}>
        Complete Offer Builder →
      </button>
    </div>
  )
}

export default Step8_GrandSlam
