-- Add challenge_name column to founder_dna_sessions
-- Stores the catchy, fun name generated by the AI for each challenge
ALTER TABLE founder_dna_sessions ADD COLUMN IF NOT EXISTS challenge_name TEXT;
